---
title: "Devnotes"
knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
---

### R pkg dev

| Command                               | Comment                                                 | Shortcut          |
| ------------------------------------- | ------------------------------------------------------- | ----------------- |
| `devtools::check()`                   | build and check the pkg                                 | `Cmd + Shift + E` |
| `devtools::load_all()`                | load the pkg                                            | `Cmd + Shift + L` |
| `devtools::document()`                | document the pkg                                        | `Cmd + Shift + D` |
| `pak::local_install(upgrade = FALSE)` | install the pkg into the first library of `.libPaths()` | `Cmd + Shift + B` |

### conda

| Command                                                                                 | Comment                                                           |
| --------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| `conda install foo -c bar`                                                              | install pkg `foo` from channel `bar`                              |
| `conda create --file env.yml --prefix ./bar`                                            | install conda pkgs listed in `env.yml` into the `./bar` directory |
| `conda info -e`                                                                         | list conda environments installed on this machine                 |
| `rattler-build build -r recipe.yaml --output-dir ${HOME}/tmp`                           | build conda pkg from a recipe file                                |
| `rattler-build upload anaconda -o umccr --api-key <xxx> ${HOME}/tmp/r-tidywigits.conda` | upload conda pkg to anaconda                                      |

### pkgdown

| Command                                  | Comment                        |
| ---------------------------------------- | ------------------------------ |
| `pkgdown::build_site()`                  | builds entire site             |
| `pkgdown::build_articles(quiet = FALSE)` | builds vignettes in debug mode |
| `pkgdown::build_article("foo")`          | builds foo vignette only       |

### Debugging R6 private methods

For private methods, reach into `.__enclos_env__$private` (flags that instance
only):

```r
devtools::load_all()
path <- system.file("extdata/tool1", package = "nemo")
t <- Tool$new(name = "tool1", pkg = "nemo", path = path)

debugonce(t$.__enclos_env__$private$build_d_write)
t$run(output_dir = tempdir(), format = "parquet") # breaks on first call
```

Call private methods standalone:

```r
row <- t$list_files()[1, ]
row$tidy <- list(t$.__enclos_env__$private$dispatch_tidy(row$path, row$parser))
d_write <- t$.__enclos_env__$private$build_d_write(
  row,
  tempdir(),
  NULL,
  NULL,
  FALSE
)
```

### Data Version Control

[DVC](https://dvc.org/) keeps test/example data in remote storage (GDrive, S3,
R2), tracked in `git`. Run `dvc pull` before tests, examples or vignettes.

| Command                                                                      | Comments                                |
| ---------------------------------------------------------------------------- | --------------------------------------- |
| `dvc init`                                                                   | initialise dvc                          |
| `dvc remote add -d storage gdrive://<...>`                                   | add GDrive remote                       |
| `dvc remote add -d my_r2 s3://<...>`                                         | add Cloudflare R2 remote                |
| `dvc remote modify my_r2 endpointurl https://<...>.r2.cloudflarestorage.com` | add Cloudflare R2 remote endpointurl    |
| `dvc remote list`                                                            | list all remotes                        |
| `dvc check-ignore *`                                                         | check what is dvc-ignored               |
| `dvc list https://github.com/tidywf/tidywigits inst/extdata`                 | list dvc'ed data                        |
| `dvc add path/to/folder`                                                     | adds `folder` (and its contents) to dvc |
| `dvc add path/to/file.txt`                                                   | adds `file.txt` to dvc                  |
| `dvc push`                                                                   | pushes dvc data to remote               |
| `dvc pull`                                                                   | pulls dvc data from remote              |
