# Generated by roxytest: do not edit by hand!

# File R/cli_sync.R: @testexamples

test_that("Function cli_sync_parse_args() @ L53", {
  
  args <- list(
    src = "s3://bucket/run1", dest = tempfile(), workflow = NULL,
    dryrun = FALSE, show_patterns = TRUE, quiet = FALSE
  )
  out <- capture.output(cli_sync_parse_args(args, wf = "workflow1"))
  expect_true(any(grepl("^ex\t\\*$", out)))
})


test_that("Function cli_nemo_sync() @ L91", {
  
  out <- capture.output(
    cli_nemo_sync(
      src = "s3://bucket/run1", dest = tempfile(),
      workflow = "workflow1", show_patterns = TRUE
    )
  )
  expect_true(any(grepl("^ex\t\\*$", out)))
  expect_error(cli_nemo_sync("s3://b/r", tempfile(), "notaworkflow"))
})

