# Generated by roxytest: do not edit by hand!

# File R/Tool.R: @testexamples

test_that("Function Tool() @ L81", {
  
  fs::path(tempdir(), letters[1:5]) |>
    fs::file_temp_push() |>
    fs::dir_create()
  name <- "tool1"; pkg <- "nemo";
  path <- system.file("extdata/tool1", package = "nemo")
  toolA <- Tool$new(name = name, pkg = pkg, path = path)
  toolA$files
  toolA$filter_files(exclude = "tool1_table3"); toolA$files # note the exclusion this time
  toolA$list_files()
  
  toolB <- Tool$new(name = name, pkg = pkg, path = path)$
    filter_files(include = "tool1_table1")
  toolB$files
  # tidy + write
  toolC <- Tool$new(name = name, pkg = pkg, path = path)$
    filter_files(exclude = "tool1_table5")$
    tidy()
  toolC$files
  toolC$tbls # note the tidy column
  dir1 <- fs::file_temp(); dir2 <- fs::file_temp()
  toolC$write(diro = dir1, format = "parquet", input_id = "run1")
  (lfC <- list.files(dir1, full.names = TRUE))
  
  # nemofy
  toolD <- Tool$new(name = name, pkg = pkg, path = path)$
    filter_files(exclude = "tool1_table5")$
    nemofy(diro = dir2, format = "parquet", input_id = "run2")
  (lfD <- list.files(dir2, full.names = TRUE))
  
  
  # filter_files: table3 excluded, other parsers present
  expect_false("tool1_table3" %in% toolA$files$tool_parser)
  expect_true(all(c("tool1_table1", "tool1_table2", "tool1_table4") %in% toolA$files$tool_parser))
  expect_equal(unique(toolB$files$tool_parser), "tool1_table1")
  # toolC: table5 excluded, table3 retained
  expect_false("tool1_table5" %in% toolC$files$tool_parser)
  expect_true("tool1_table3" %in% toolC$files$tool_parser)
  expect_error(
    toolB$filter_files(include = "tool1_table1", exclude = "tool1_table3"),
    "You cannot define both include and exclude"
  )
  # tidy: structure and column names
  expect_false(is.null(toolC$tbls))
  expect_named(
    toolC$tbls,
    c(
      "tool_parser", "parser", "bname", "size", "lastmodified", "path",
      "pattern", "prefix", "group", "tidy"
    )
  )
  # table4: two versions parsed with correct column counts
  t4 <- toolC$tbls |> dplyr::filter(tool_parser == "tool1_table4")
  expect_equal(nrow(t4), 2)
  t4_ncols <- purrr::map_int(t4$tidy, \(x) ncol(x$data[[1]]))
  expect_setequal(t4_ncols, c(3L, 5L))
  # write: two table4 output files (one per version)
  expect_equal(sum(grepl("table4", lfC)), 2)
  expect_named(toolD, c("raw_path", "tool_parser", "prefix", "tidy_data", "tbl_name", "outpath"))
})

