# Generated by roxytest: do not edit by hand!

# File R/Workflow1.R: @testexamples

test_that("Function Workflow1() @ L22", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  wf <- Workflow1$new(path)
  (lf_all <- wf$list_files())
  dir1 <- tempdir()
  wf$nemofy(diro = dir1, format = "parquet", input_id = "run1")
  (lf <- list.files(dir1, pattern = "tool1.*parquet", full.names = TRUE))
  # initialize
  expect_equal(length(wf$tools), 1)
  expect_equal(wf$tools[[1]]$name, "tool1")
  # list_files
  expect_equal(nrow(lf_all), 7)
  # nemofy
  expect_equal(length(lf), 7)
})

