# Generated by roxytest: do not edit by hand!

# File R/Workflow.R: @testexamples

test_that("Function Workflow() @ L58", {
  
  fs::path(tempdir(), letters[1:5]) |>
    fs::file_temp_push() |>
    fs::dir_create()
  path <- system.file("extdata/tool1", package = "nemo")
  tools <- list(tool1 = Tool1)
  wf <- Workflow$new(name = "wf1", path = path, tools = tools)
  (lf_all <- wf$list_files())
  wf$filter_files(exclude = "tool1_table5")
  wf$tidy()
  (tbls <- wf$get_tbls())
  (rs <- wf$get_raw_schemas_all())
  dir1 <- fs::file_temp(); dir2 <- fs::file_temp()
  wf$write(diro = dir1, format = "parquet", input_id = "run1")
  (lf1 <- list.files(dir1, pattern = "tool1.*parquet", full.names = TRUE))
  (meta <- wf$get_metadata(input_id = "run1", output_id = "out1", output_dir = dir1))
  wf2 <- Workflow$new(name = "wf2", path = path, tools = tools)
  wf2$nemofy(diro = dir2, format = "parquet", input_id = "run2")
  (lf2 <- list.files(dir2, pattern = "tool1.*parquet", full.names = TRUE))
  # list_files
  nms1 <- c(
    "tool_parser", "parser", "bname", "size", "lastmodified", "path",
    "pattern", "prefix", "group"
  )
  expect_equal(nrow(lf_all), 6)
  expect_named(lf_all, nms1)
  # filter_files + tidy + get_tbls
  expect_equal(nrow(tbls), 5)
  expect_named(tbls, c(nms1, "tidy"))
  # get_raw_schemas_all
  expect_named(rs, c("tool", "name", "tbl_description", "version", "schema"))
  # write + written_files
  expect_equal(length(lf1), 5)
  expect_named(wf$written_files, c("tool_parser", "prefix", "tidy_data", "tbl_name", "outpath"))
  # get_metadata
  expect_named(meta, c("input_id", "output_id", "input_dir", "output_dir", "pkg_versions", "files"))
  # nemofy
  expect_equal(length(lf2), 6)
})

