# Generated by roxytest: do not edit by hand!

# File R/utils.R: @testexamples

test_that("Function list_files_dir() @ L29", {
  
  d <- system.file("R", package = "nemo")
  x <- list_files_dir(d)
  # symlinked files are included
  d2 <- fs::dir_create(tempfile())
  f <- fs::file_create(file.path(d2, "real.tsv"))
  fs::link_create(f, file.path(d2, "link.tsv"))
  x2 <- list_files_dir(d2)
  expect_equal(names(x), c("bname", "size", "lastmodified", "path"))
  expect_setequal(x2$bname, c("real.tsv", "link.tsv"))
})


test_that("Function get_tbl_version_attr() @ L71", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  path2 <- file.path(path, "v1.2.3", "sampleA.tool1.table1.tsv")
  x <- Tool1$new(path)$tidy(keep_raw = TRUE)
  ind <- which(x$get_tbls()$path == path2)
  stopifnot(length(ind) == 1)
  (v <- get_tbl_version_attr(x$get_tbls()$raw[[ind]]))
  
  expect_equal(v, "v1.2.3")
})


test_that("Function set_tbl_version_attr() @ L95", {
  
  d <- tibble::tibble(a = 1:3, b = letters[1:3])
  v <- "v1.2.3"
  d <- set_tbl_version_attr(d, v)
  (a <- attr(d, "file_version"))
  
  expect_equal(a, v)
})


test_that("Function empty_tbl() @ L116", {
  
  (x <- empty_tbl(cnames = c("a", "b", "c")))
  expect_equal(nrow(x), 0)
})


test_that("Function nemoverse_wf_dispatch() @ L157", {
  
  (fun <- nemoverse_wf_dispatch("workflow1"))
  expect_identical(fun, Workflow1)
  expect_error(nemoverse_wf_dispatch("foo"))
})


test_that("Function read_parquet_grep() @ L208", {
  
  odir <- fs::dir_create(tempfile())
  arrow::write_parquet(data.frame(x = 1L), file.path(odir, "a_1.parquet"))
  arrow::write_parquet(data.frame(x = 2L), file.path(odir, "a_2.parquet"))
  lf <- list.files(odir)
  (x <- read_parquet_grep(odir, lf, "a_1"))
  (y <- read_parquet_grep(odir, lf, "^a_", first = TRUE))
  expect_equal(x$x, 1L)
  expect_equal(y$x, 1L)
  expect_error(read_parquet_grep(odir, lf, "^a_"), "2 files match")
  expect_error(read_parquet_grep(odir, lf, "nomatch"), "No file matches")
  expect_error(read_parquet_grep(odir, lf, "nomatch", first = TRUE), "No file matches")
})


test_that("Function pkg_found() @ L235", {
  
  pkg_found("base")
  pkg_found("somefakepackagename")
  expect_true(pkg_found("base"))
  expect_false(pkg_found("somefakepackagename"))
})

