# Generated by roxytest: do not edit by hand!

# File R/Tool.R: @testexamples

test_that("Function Tool() @ L116", {
  
  fs::path(tempdir(), letters[1:5]) |>
    fs::file_temp_push() |>
    fs::dir_create()
  name <- "tool1"; pkg <- "nemo";
  path <- system.file("extdata/tool1", package = "nemo")
  toolA <- Tool$new(name = name, pkg = pkg, path = path)
  toolA$files
  toolA$filter_files(exclude = "tool1_table3"); toolA$files # note the exclusion this time
  toolA$list_files()
  
  toolB <- Tool$new(name = name, pkg = pkg, path = path)$
    filter_files(include = "tool1_table1")
  toolB$files
  # tidy + write
  toolC <- Tool$new(name = name, pkg = pkg, path = path)$
    filter_files(exclude = "tool1_table5")$
    tidy()
  toolC$files
  toolC$tbls # note the tidy column
  dir1 <- fs::file_temp(); dir2 <- fs::file_temp()
  toolC$write(output_dir = dir1, format = "parquet", input_id = "run1")
  (lfC <- list.files(dir1, full.names = TRUE))
  
  # wrangle
  toolD <- Tool$new(name = name, pkg = pkg, path = path)$
    filter_files(exclude = "tool1_table5")$
    wrangle(output_dir = dir2, format = "parquet", input_id = "run2")
  (lfD <- list.files(dir2, full.names = TRUE))
  
  
  # filter_files: table3 excluded, other parsers present
  expect_false("tool1_table3" %in% toolA$files$tool_parser)
  expect_true(all(c("tool1_table1", "tool1_table2", "tool1_table4") %in% toolA$files$tool_parser))
  expect_equal(unique(toolB$files$tool_parser), "tool1_table1")
  # toolC: table5 excluded, table3 retained
  expect_false("tool1_table5" %in% toolC$files$tool_parser)
  expect_true("tool1_table3" %in% toolC$files$tool_parser)
  expect_error(
    toolB$filter_files(include = "tool1_table1", exclude = "tool1_table3"),
    "You cannot define both include and exclude"
  )
  # initialize: non-scalar name/pkg
  expect_error(Tool$new(name = c("a", "b"), pkg = pkg, path = path))
  expect_error(Tool$new(name = name, pkg = c("nemo", "nemo"), path = path))
  # filter_files: unknown parsers
  expect_error(
    Tool$new(name = name, pkg = pkg, path = path)$filter_files(include = "tool1_nonexistent"),
    "unknown tool_parser"
  )
  expect_error(
    Tool$new(name = name, pkg = pkg, path = path)$filter_files(exclude = "tool1_nonexistent"),
    "unknown tool_parser"
  )
  # write: invalid format
  expect_error(toolC$write(output_dir = tempdir(), format = "invalid"), "Invalid format")
  # tidy: structure and column names
  expect_false(is.null(toolC$tbls))
  expect_named(
    toolC$tbls,
    c(
      "tool_parser", "parser", "bname", "size", "lastmodified", "path",
      "pattern", "prefix", "group", "tidy"
    )
  )
  # table4: two versions parsed with correct column counts
  t4 <- toolC$tbls |> dplyr::filter(tool_parser == "tool1_table4")
  expect_equal(nrow(t4), 2)
  t4_ncols <- purrr::map_int(t4$tidy, \(x) ncol(x$data[[1]]))
  expect_setequal(t4_ncols, c(3L, 5L))
  # write: two table4 output files (one per version)
  expect_equal(sum(grepl("table4", lfC)), 2)
  # write: metadata_tool1.parquet written for standalone Tool
  meta_c <- arrow::read_parquet(file.path(dir1, "metadata_tool1.parquet"))
  expect_named(meta_c, c("input_id", "output_id", "input_dirs", "output_dir", "pkg_versions", "files"))
  expect_equal(meta_c$input_id, "run1")
  expect_named(toolD$written_files, c("raw_path", "tool_parser", "prefix", "tidy_data", "tbl_name", "outpath"))
  # input_id / output_id / prefix_include column tests
  toolE <- Tool$new(name = name, pkg = pkg, path = path)$
    filter_files(include = "tool1_table1")$tidy()
  read_pq <- function(d) {
    fs <- list.files(d, pattern = "[.]parquet$", full.names = TRUE)
    arrow::read_parquet(fs[!grepl("^metadata_", basename(fs))][1])
  }
  dE0 <- fs::file_temp(); toolE$write(output_dir = dE0, format = "parquet")
  dEi <- fs::file_temp(); toolE$write(output_dir = dEi, format = "parquet", input_id = "run1")
  dEo <- fs::file_temp(); toolE$write(output_dir = dEo, format = "parquet", output_id = "out1")
  dEp <- fs::file_temp(); toolE$write(output_dir = dEp, format = "parquet", prefix_include = TRUE)
  dEa <- fs::file_temp(); toolE$write(output_dir = dEa, format = "parquet", input_id = "run1", output_id = "out1", prefix_include = TRUE)
  expect_false(any(c("input_id", "output_id", "input_prefix") %in% names(read_pq(dE0))))
  expect_equal(read_pq(dEi)$input_id[1], "run1")
  expect_equal(read_pq(dEo)$output_id[1], "out1")
  expect_true("input_prefix" %in% names(read_pq(dEp)))
  expect_equal(names(read_pq(dEa))[1:3], c("input_id", "input_prefix", "output_id"))
})

