# Generated by roxytest: do not edit by hand!

# File R/assert.R: @testexamples

test_that("Function nemo_assert_out_fmt() @ L59", {
  
  nemo_assert_out_fmt("tsv")
  expect_true(nemo_assert_out_fmt("tsv"))
  expect_error(nemo_assert_out_fmt("foo"))
  expect_error(nemo_assert_out_fmt(c("tsv", "csv")))
})

