# Generated by roxytest: do not edit by hand!

# File R/schema_check.R: @testexamples

test_that("Function nemo_schema_check() @ L31", {
  
  nemo_schema_check("tool1", pkg = "nemo")
  # invalid schema example: bad ftype, non-snake_case tidy, invalid type
  bad_cfg <- list(tables = list(
    mytable = list(
      description = "x", pattern = "\\.tsv$", ftype = "bad_ftype",
      columns = list(list(
        raw = "Col1", tidy = "BadTidy", type = "str",
        description = "col1", versions = list("latest")
      ))
    )
  ))
  res <- nemo_schema_check("tool1", pkg = "nemo")
  expect_s3_class(res, "tbl_df")
  expect_equal(nrow(res), 0L)
  #.schema_check_structure(bad_cfg)
})

