# Generated by roxytest: do not edit by hand!

# File R/log.R: @testexamples

test_that("Function nemo_log() @ L69", {
  
  nemo_log("INFO", "Tidying %s", "dir1")
  withr::with_envvar(c(NEMO_LOG_ENABLE = "TRUE", NEMO_LOG_LEVEL = "debug"), {
    expect_output(nemo_log("DEBUG", "hi %d", 1L), "nemo DEBUG: hi 1")
  })
  withr::with_envvar(c(NEMO_LOG_ENABLE = "TRUE", NEMO_LOG_LEVEL = "WARN"), {
    expect_silent(nemo_log("INFO", "hidden"))
  })
  withr::with_envvar(c(NEMO_LOG_ENABLE = "TRUE", NEMO_LOG_LEVEL = "bogus"), {
    expect_warning(nemo_log("INFO", "x"), "Invalid NEMO_LOG_LEVEL")
    expect_no_warning(nemo_log("INFO", "x"))
  })
  withr::with_envvar(c(NEMO_LOG_ENABLE = "FALSE"), {
    expect_silent(nemo_log("INFO", "hidden"))
  })
})

