# Generated by roxytest: do not edit by hand!

# File R/cli_tidy.R: @testexamples

test_that("Function cli_tidy_parse_args() @ L65", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  args <- list(
    format = "parquet", in_dir = path, out_dir = tempfile(),
    id = "run1", workflow = NULL, dbname = NULL, dbuser = NULL,
    include = NULL, exclude = NULL, quiet = FALSE
  )
  cli_tidy_parse_args(args, wf = "workflow1")
  expect_no_error(cli_tidy_parse_args(args, wf = "workflow1"))
  args_quiet <- modifyList(args, list(quiet = TRUE, out_dir = tempfile()))
  expect_no_error(cli_tidy_parse_args(args_quiet, wf = "workflow1"))
  args_no_dir <- modifyList(args, list(out_dir = NULL))
  expect_error(cli_tidy_parse_args(args_no_dir, wf = "workflow1"))
  args_include <- modifyList(args, list(include = "tool1_table1,tool1_table2", out_dir = tempfile()))
  expect_no_error(cli_tidy_parse_args(args_include, wf = "workflow1"))
})


test_that("Function cli_nemo_tidy() @ L143", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  out <- tempfile()
  res <- cli_nemo_tidy(
    workflow = "workflow1", in_dir = path, out_dir = out,
    out_format = "parquet", id = "run1",
    dbname = NULL, dbuser = NULL, include = NULL, exclude = NULL
  )
  expect_true(inherits(res, "Workflow"))
  expect_true(length(res$written_files) > 0)
  expect_error(cli_nemo_tidy(
    workflow = "workflow1", in_dir = path, out_dir = tempfile(),
    out_format = "badformat", id = "run1",
    dbname = NULL, dbuser = NULL, include = NULL, exclude = NULL
  ))
  expect_error(cli_nemo_tidy(
    workflow = "notaworkflow", in_dir = path, out_dir = tempfile(),
    out_format = "parquet", id = "run1",
    dbname = NULL, dbuser = NULL, include = NULL, exclude = NULL
  ))
})

