# Generated by roxytest: do not edit by hand!

# File R/parse.R: @testexamples

test_that("Function parse_file() @ L27", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  x <- Tool$new("tool1", pkg = "nemo", path)
  schemas_all <- x$raw_schemas_all
  pname <- "table1"
  fpath <- file.path(path, "latest", "sampleA.tool1.table1.tsv")
  (d <- parse_file(fpath, pname, schemas_all))
  
  expect_equal(names(d)[1:3], c("SampleID", "Chromosome", "Start"))
})


test_that("Function parse_file_nohead() @ L84", {
  
  path <- system.file("extdata/tool1", package = "nemo")
  x <- Tool$new("tool1", pkg = "nemo", path)
  schemas_all <- x$raw_schemas_all
  pname <- "table4"
  fpath_latest <- file.path(path, "latest", "sampleA.tool1.table4.tsv")
  fpath_v1 <- file.path(path, "v1.0.0", "sampleA.tool1.table4.tsv")
  schema_latest <- schemas_all |>
    dplyr::filter(.data$name == pname, .data$version == "latest") |>
    dplyr::select("version", "schema")
  schema_v1 <- schemas_all |>
    dplyr::filter(.data$name == pname, .data$version == "v1.0.0") |>
    dplyr::select("version", "schema")
  (d_latest <- parse_file_nohead(fpath_latest, schema_latest))
  (d_v1 <- parse_file_nohead(fpath_v1, schema_v1))
  
  expect_equal(ncol(d_latest), 5)
  expect_equal(ncol(d_v1), 3)
  expect_equal(names(d_latest), c("X1", "X2", "X3", "X4", "X5"))
  expect_equal(names(d_v1), c("X1", "X2", "X3"))
  expect_equal(attr(d_latest, "file_version"), "latest")
  expect_equal(attr(d_v1, "file_version"), "v1.0.0")
})


test_that("Function file_hdr() @ L129", {
  
  dir1 <- system.file("extdata/tool1", package = "nemo")
  fpath <- file.path(dir1, "latest", "sampleA.tool1.table1.tsv")
  (hdr <- file_hdr(fpath))
  
  expect_equal(hdr[1:2], c("SampleID", "Chromosome"))
})


test_that("Function schema_guess() @ L170", {
  
  dir1 <- system.file("extdata/tool1", package = "nemo")
  fpath1 <- file.path(dir1, "latest", "sampleA.tool1.table1.tsv")
  fpath2 <- file.path(dir1, "v1.2.3", "sampleA.tool1.table1.tsv")
  pname <- "table1"
  cnames1 <- file_hdr(fpath1)
  cnames2 <- file_hdr(fpath2)
  conf <- Config$new("tool1", pkg = "nemo")
  schemas_all <- conf$get_schemas_all("raw")
  (s1 <- schema_guess(pname, cnames1, schemas_all))
  (s2 <- schema_guess(pname, cnames2, schemas_all))
  
  expect_equal(length(s1), 2)
  expect_equal(s1[["version"]], "latest")
  expect_equal(s2[["version"]], "v1.2.3")
})


test_that("Function parse_file_keyvalue() @ L226", {
  
  dir1 <- system.file("extdata/tool1", package = "nemo")
  fpath <- file.path(dir1, "latest", "sampleA.tool1.table3.tsv")
  x <- Tool1$new(dir1)
  schemas_all <- x$raw_schemas_all
  pname <- "table3"
  (d <- parse_file_keyvalue(fpath, pname, schemas_all))
  
  expect_equal(names(d)[1:2], c("SampleID", "QCStatus"))
})

