# Generated by roxytest: do not edit by hand!

# File R/schema_vis.R: @testexamples

test_that("Function nemo_schemavis_data() @ L143", {
  
  d <- nemo_schemavis_data("tool1", pkg = "nemo")
  expect_s3_class(d, "tbl_df")
  expect_true(all(c("tool", "tbl", "description", "ftype", "glob", "columns",
    "versions", "n_cols", "col_names") %in% names(d)))
  expect_equal(d$n_cols[d$tbl == "table1"], 6L)
  expect_true(grepl("sample_id", d$col_names[d$tbl == "table1"]))
})

