# Generated by roxytest: do not edit by hand!

# File R/Config.R: @testexamples

test_that("Function Config() @ L57", {
  
  tool <- "tool1"
  pkg <- "nemo"
  conf <- Config$new(tool, pkg)
  (patterns <- conf$get_patterns())
  (ftypes <- conf$get_ftypes())
  (ftype1 <- conf$get_ftype("table1"))
  (descr <- conf$get_descriptions())
  (rs <- conf$get_schemas_all("raw"))
  (ts <- conf$get_schemas_all("tidy"))
  (s1 <- conf$get_schema("table1"))
  conf$get_schema("table1", v = "v1.2.3")
  conf$get_schema("table1", raw_or_tidy = "tidy")
  conf$are_schemas_valid()
  (cm <- conf$get_col_map("table5"))
  
  # initialize
  expect_error(Config$new("foo", pkg))
  # get_patterns
  expect_equal(nrow(patterns), 5)
  # get_ftypes
  expect_equal(dplyr::distinct(ftypes, .data$ftype) |> nrow(), 4)
  # get_ftype
  expect_equal(ftype1, "txt")
  # get_descriptions
  expect_equal(nrow(descr), 5)
  # get_schemas_all
  expect_equal(dplyr::filter(rs, .data$name == "table1") |> nrow(), 3)
  expect_equal(dplyr::filter(ts, .data$name == "table1") |> nrow(), 3)
  # get_schema
  expect_named(s1, c("version", "field", "type"))
  expect_equal(nrow(conf$get_schema("table1", v = "v1.2.3")), 5)
  expect_equal(nrow(conf$get_schema("table1", v = "v4.5.6")), 4)
  expect_error(conf$get_schema("foo"))
  expect_error(conf$get_schema("table1", v = "foo"))
  # are_schemas_valid
  expect_true(conf$are_schemas_valid())
  # get_col_map
  expect_named(cm, c("raw", "tidy", "type", "description"))
})


test_that("Function config_prep_raw_schema() @ L320", {
  
  path <- system.file("extdata", "tool1/latest/sampleA.tool1.table1.tsv", package = "nemo")
  (x <- config_prep_raw_schema(path = path, delim = "\t"))
  expect_equal(x[1, "field", drop = T], "'SampleID'")
})


test_that("Function config_prep_raw() @ L365", {
  
  path <- system.file("extdata", "tool1/latest/sampleA.tool1.table1.tsv", package = "nemo")
  name <- "table1"
  descr <- "Table1 from Tool1."
  pat <- "\\.tool1\\.table1\\.tsv$"
  l <- config_prep_raw(path, name, descr, pat)
  expect_equal(names(l[[1]]), c("description", "pattern", "ftype", "schema"))
})

