# Generated by roxytest: do not edit by hand!

# File R/schema_vis.R: @testexamples

test_that("Function nemo_schema_data() @ L196", {
  
  nemo_schema_data("tool1", pkg = "nemo")
  expect_s3_class(nemo_schema_data("tool1", pkg = "nemo"), "tbl_df")
  expect_true(all(c("n", "tool", "tbl", "schema_version", "description") %in%
    names(nemo_schema_data("tool1", pkg = "nemo"))))
})

