# Generated by roxytest: do not edit by hand!

# File R/sync.R: @testexamples

test_that("Function wf_sync_patterns() @ L34", {
  
  (pats <- wf_sync_patterns("workflow1"))
  expect_equal(names(pats), c("inex", "pat"))
  expect_equal(pats$inex[1], "ex")
  expect_equal(pats$pat[1], "*")
  expect_gt(nrow(pats), 1)
  expect_error(wf_sync_patterns("notaworkflow"))
})


test_that("Function glob_to_regex() @ L84", {
  
  (r1 <- glob_to_regex("*.purple.qc"))
  (r2 <- glob_to_regex("*purple/*.purple.qc"))
  expect_true(grepl(r1, "sample1.purple.qc"))
  expect_true(grepl(r1, "a/b/sample1.purple.qc"))
  expect_false(grepl(r1, "sample1.purple.qc.bak"))
  expect_true(grepl(r2, "run/purple/sample1.purple.qc"))
  expect_false(grepl(r2, "run/amber/sample1.purple.qc"))
  expect_error(glob_to_regex(c("a", "b")))
})


test_that("Function schema_glob_check() @ L125", {
  
  (bad <- schema_glob_check("nemo"))
  expect_equal(nrow(bad), 0)
  expect_named(bad, c("tool", "table", "file"))
  expect_error(schema_glob_check("nemo", fixture_dir = "/no/such/dir"))
})

