# Generated by roxytest: do not edit by hand!

# File R/schema_vis.R: @testexamples

test_that("Function nemo_schemavis_data() @ L194", {
  
  expect_s3_class(nemo_schemavis_data("tool1", pkg = "nemo"), "tbl_df")
  expect_true(all(c("n", "tool", "tbl", "schema_version", "description") %in%
    names(nemo_schemavis_data("tool1", pkg = "nemo"))))
})

