name: conda-docs

on:
  push:
    tags:
      - "v*"

jobs:
  prep:
    name: 📋 Version
    runs-on: ubuntu-latest
    outputs:
      pkg_version: ${{ steps.v.outputs.pkg_version }}
    steps:
      - id: v
        run: echo "pkg_version=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

  condarise:
    name: 🐍 Condarise
    needs: [prep]
    uses: tidywf/actions/.github/workflows/condarise.yaml@main
    permissions:
      contents: write
    with:
      pkg_name: nemo
      pkg_version: ${{ needs.prep.outputs.pkg_version }}
    secrets: inherit

  pkgdownise:
    name: 🌐 Pkgdownise
    needs: [prep, condarise]
    uses: tidywf/actions/.github/workflows/pkgdownise.yaml@main
    permissions:
      contents: write
    with:
      pkg_name: nemo
      pkg_version: ${{ needs.prep.outputs.pkg_version }}
    secrets: inherit
