name: conda-docs

on:
  push:
    branches:
      - main
      - dev

jobs:
  version:
    name: 📋 Get version
    if: "startsWith(github.event.head_commit.message, 'Bump version:')"
    uses: tidywf/actions/.github/workflows/version.yaml@main

  condarise:
    name: 🐍 Condarise
    needs: [version]
    uses: tidywf/actions/.github/workflows/condarise.yaml@main
    permissions:
      contents: write
    with:
      pkg_name: nemo
      pkg_version: ${{ needs.version.outputs.pkg_version }}
    secrets: inherit

  tag:
    name: 🔖 Tag
    needs: [condarise, version]
    uses: tidywf/actions/.github/workflows/tag.yaml@main
    permissions:
      contents: write
    with:
      pkg_version: ${{ needs.version.outputs.pkg_version }}
    secrets: inherit

  pkgdownise:
    name: 🌐 Pkgdownise
    needs: [tag, version]
    uses: tidywf/actions/.github/workflows/pkgdownise.yaml@main
    permissions:
      contents: write
    with:
      pkg_name: nemo
      pkg_version: ${{ needs.version.outputs.pkg_version }}
    secrets: inherit
